name: Build 🛠

on: workflow_dispatch

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  buildAndTestForSomePlatforms:
    name: Android Build ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildsPath:
          - builds
        unityVersion:
          - 2020.1.4f1
        targetPlatform:
          - Android
        projectName:
          - plant-shop-tycoon
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: true
      - uses: actions/cache@v2.1.3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
      - uses: webbertakken/unity-builder@v2.0-alpha-3
        id: build
        with:
          versioning: Semantic
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: ${{ matrix.buildsPath }}
          buildName: ${{ matrix.projectName }}
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: ${{ matrix.targetPlatform }}-${{ steps.build.outputs.buildVersion }}
          path: ${{ matrix.buildsPath }}/${{ matrix.targetPlatform }}
