name: Actions 😎

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity-actions
        unityVersion:
          - 2020.1.4f1
        targetPlatform:
          - iOS
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        id: tests
        with:
          testMode: editmode
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: test-artifacts
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: Test results (all modes)
          path: ${{ steps.tests.outputs.artifactsPath }}
