name: Android Build 🛠

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Version'
        required: true
        default: '0.0.1'

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  BUILD_NUMBER: ${{ github.run_number }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  buildAndTestForSomePlatforms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - unity-actions
        buildsPath:
          - home/runner/work/botany-tycoon/builds
        unityVersion:
          - 2020.1.4f1
        targetPlatform:
          - Android
        projectName:
          - plant-shop-tycoon
        fullVersion:
          - ${{ github.event.inputs.version }}b${{ env.BUILD_NUMBER }}
    name: ${{ matrix.targetPlatform }} Build ${{ matrix.fullVersion }}
    steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.4
#         with:
#           lfs: true
#       - name: Cache
#         uses: actions/cache@v2.1.3
#         with:
#           path: ${{ matrix.projectPath }}/Library
#           key: Library-${{ matrix.targetPlatform }}
#           restore-keys: |
#             Library-${{ matrix.targetPlatform }}
#       - name: Unity Build
#         uses: webbertakken/unity-builder@v2.0-alpha-3
#         id: build
#         with:
#           versioning: Custom
#           projectPath: ${{ matrix.projectPath }}
#           unityVersion: ${{ matrix.unityVersion }}
#           targetPlatform: ${{ matrix.targetPlatform }}
#           buildsPath: ${{ matrix.buildsPath }}
#           buildName: ${{ matrix.projectName }}
#           buildMethod: Editor.BuildScript.CustomBuild
#           version: ${{ github.event.inputs.version }}b${{ env.BUILD_NUMBER }}
#           androidVersionCode: ${{ env.BUILD_NUMBER }}
#           allowDirtyBuild: true
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v2.2.1
#         with:
#           name: ${{ matrix.targetPlatform }}-${{ steps.build.outputs.buildVersion }}
#           path: ${{ matrix.buildsPath }}/${{ matrix.targetPlatform }}
      - name: Test
        id: Test
        run: echo TEST
      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        with:
          job_name: ${{ matrix.targetPlatform }} Build ${{ matrix.fullVersion }}
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,ref,workflow,job,took        
